### PR TITLE
add cli support for swan

### PR DESCRIPTION
**Pull request by cmingxu**
Signed-off-by: kevin xu <cming.xu@gmail.com>

### CODE REVIEW

**Comment by upccup** [comment]
SGTM

**Comment by cmingxu** [comment]
Any update for this PR ? @upccup @pwzgorilla

**Comment by cmingxu** [comment]
@upccup @pwzgorilla Just want remind you guys that this PR is a block for my succeeding commits, I want a quick merge/close/comments on this, Thanks

**Comment by upccup** [comment]
+1

**Comment by pwzgorilla** [comment]
@cmingxu cli那个 那样设计不太行，因为是要设计swancfg这样的cli工具对比borgcfg。

**Comment by cmingxu** [comment]
@pwzgorilla  I see. So you want 1, make swan server run in server mode and only accessible by API; 2 make configuration like docker daemon does through file .

If so, that make sense to me.

**Pull request closed without merging**
