### PR TITLE
add custom log for context

### PR DESCRIPTION
**Pull request by upccup**

### CODE REVIEW

**Comment by pwzgorilla** [comment]
@upccup 这是干嘛的

**Comment by upccup** [comment]
@pwzgorilla  To define this locally to a package to get package tagged log  messages.

I will use it in the following commit.

**Comment by pwzgorilla** [comment]
@upccup 那为啥不跟following commit一起提交？还是说先不用管这个pr？

**Comment by upccup** [comment]
@pwzgorilla  Is a single module.  if no error  need merge.

**Comment by pwzgorilla** [comment]
@upccup 这两个提交是相关的吗？是的话先rebase。

**Comment by upccup** [comment]
one commit is custom code and another is  add 3rd pkgs .

**Comment by upccup** [comment]
@pwzgorilla @cmingxu any  other question?

**Comment by pwzgorilla** [comment]
@upccup 那你就merge了吧，虽然看不懂你要干嘛。

**Pull request merged**
