### PR TITLE
add `zk` support

### PR DESCRIPTION
**Pull request by pwzgorilla**

### CODE REVIEW

**Comment by cmingxu** [comment]
@pwzgorilla 
I don't think there is no need for Swan to connect with Zookeeper directly, as swan is merely a mesos framework. As a framework swan can only interact with Mesos Cluster through CPP lib or HTTP API. 

We should decouple swan and mesos as much as possible.

**Comment by pwzgorilla** [comment]
@cmingxu  Mr. wang wanna this feature :)

**Comment by pwzgorilla** [comment]
@cmingxu 支持也是可以的，从zk里获取mesos master leader 地址.

**Comment by cmingxu** [comment]
@pwzgorilla Let's sync up Monday.

**Comment by xiaods** [comment]
this is compatible feature to support mesos convention.  i don't think this is very important side to ask @pwzgorilla to talk about more reasonable information to introduce zk.

this is only just compatible with current mesos environment. the master maybe know or maybe stored in zookeeper. this is trivial feature. don't worry.

**Comment by upccup** [comment]
SGTM

**Pull request merged**
